# Generated by Django 2.2 on 2019-05-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VetOccupations',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('anzsco_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('weekly_pay', models.BigIntegerField(blank=True, null=True)),
                ('employment_size', models.TextField(blank=True, null=True)),
                ('future_growth', models.TextField(blank=True, null=True)),
                ('skill_level', models.TextField(blank=True, null=True)),
                ('unemployment', models.TextField(blank=True, null=True)),
                ('full_time_share', models.FloatField(blank=True, null=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('female', models.FloatField(blank=True, null=True)),
                ('high_demand', models.BigIntegerField(blank=True, null=True)),
                ('male', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vet_occupations',
                'managed': False,
            },
        ),
    ]
