# Generated by Django 2.2 on 2019-05-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VetCourses',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('course_title', models.TextField(blank=True, null=True)),
                ('course_code', models.TextField(blank=True, null=True)),
                ('qualification_level', models.TextField(blank=True, null=True)),
                ('course_type', models.TextField(blank=True, null=True)),
                ('government_subsidised', models.BigIntegerField(blank=True, null=True)),
                ('apprenticeship', models.BigIntegerField(blank=True, null=True)),
                ('traineeship', models.BigIntegerField(blank=True, null=True)),
                ('entry_requirements', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vet_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VetCoursesToOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzsco', models.BigIntegerField(blank=True, null=True)),
                ('course_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vet_courses_to_occupation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VetCoursesToProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(blank=True, null=True)),
                ('campus_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vet_courses_to_provider',
                'managed': False,
            },
        ),
    ]
