from django.db import models
from datetime import datetime

# Create your models here.
class UserBigTable(models.Model):
    email = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200, null=True)
    lastname = models.CharField(max_length=200, null=True)
    phoneNumber = models.CharField(max_length=200, null=True)
    address = models.CharField(max_length=200, null=True)
    suburb = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    password = models.CharField(max_length=200, null=True)
    actionType = models.CharField(max_length=200, null=True)
    categoryType = models.CharField(max_length=200, null=True)
    subCategoryType = models.CharField(max_length=200, null=True)
    productName = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=200, null=True)
    dateAvailable = models.DateTimeField(null=True)
    durationAvailable = models.FloatField(null=True)
    fromTime = models.FloatField(null=True)
    toTime = models.FloatField(null=True)
    availableQuanity = models.FloatField(null=True)
    dateCreated = models.DateTimeField( default=datetime.now)
    column_text_1 = models.CharField(max_length=200, null=True)
    column_text2 = models.CharField(max_length=200, null=True)
    column_text3 = models.CharField(max_length=200, null=True)
    column_text7 = models.CharField(max_length=200, null=True)
    column_num8 = models.FloatField(null=True)
    column_num4 = models.FloatField(null=True)
    column_num5 = models.FloatField(null=True)
    column_date6 = models.DateTimeField(null=True)
