# Generated by Django 2.1 on 2020-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityAssist', '0003_auto_20200410_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbigtable',
            old_name='column6',
            new_name='column_date6',
        ),
        migrations.RenameField(
            model_name='userbigtable',
            old_name='column4',
            new_name='column_num4',
        ),
        migrations.RenameField(
            model_name='userbigtable',
            old_name='column5',
            new_name='column_num5',
        ),
        migrations.RenameField(
            model_name='userbigtable',
            old_name='column8',
            new_name='column_num8',
        ),
        migrations.RenameField(
            model_name='userbigtable',
            old_name='column1',
            new_name='column_text2',
        ),
        migrations.RenameField(
            model_name='userbigtable',
            old_name='column2',
            new_name='column_text3',
        ),
        migrations.RenameField(
            model_name='userbigtable',
            old_name='column3',
            new_name='column_text7',
        ),
        migrations.RenameField(
            model_name='userbigtable',
            old_name='column7',
            new_name='column_text_1',
        ),
        migrations.RenameField(
            model_name='userbigtable',
            old_name='timeAvailable',
            new_name='durationAvailable',
        ),
        migrations.AddField(
            model_name='userbigtable',
            name='fromTime',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userbigtable',
            name='toTime',
            field=models.FloatField(null=True),
        ),
    ]
